name: CI
on:
    push:
        branches:
        - master
    pull_request:
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    flake8:
        name: Flake8
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
                . ./prepare-and-run-flake8.sh "$(basename $GITHUB_REPOSITORY)" ./test

    pytest3:
        name: Pytest Conda Py3
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: "Main Script"
            run: |
                CONDA_ENVIRONMENT=.test-conda-env-py3.yml
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
                . ./build-and-test-py-project-within-miniconda.sh

    pytest3:
        name: Pytest Firedrake
        runs-on: ubuntu-latest
        steps:
        -   uses: docker://firedrakeproject/firedrake
        -   uses: actions/checkout@v2
        -   name: "APT dependencies"
            run: |
              sudo apt update
              sudo apt install -y pocl-opencl-icd ocl-icd-opencl-dev
        -   name: "PIP dependencies"
            run: |
              source ~/firedrake/bin/activate
              "grep -v loopy requirements.txt > myreq.txt"
              pip install -r myreq.txt
              # The Firedrake container is based on Py3.6 as of 2020-10-10, which
              # doesn't have dataclasses.
              pip install pytest dataclasses
              pip install .
        -   name: "Test"
            run: |
              cd test
              python -m pytest --tb=native --junitxml=pytest.xml -rxsw test_firedrake_interop.py
                            CONDA_ENVIRONMENT=.test-conda-env-py3.yml
                            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
                            . ./build-and-test-py-project-within-miniconda.sh

    examples3:
        name: Examples Conda Py3
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: "Main Script"
            run: |
                CONDA_ENVIRONMENT=.test-conda-env-py3.yml
                USE_CONDA_BUILD=1
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-py-project-and-run-examples.sh
                . ./build-py-project-and-run-examples.sh

# vim: sw=4
